version: '3.7'

services:
  web:
    # php 8.2.5
    image: 8ct8pus/apache-php-fpm-alpine:2.0.11
    container_name: web
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN=localhost
      - DOCUMENT_ROOT=/demo/public
    volumes:
      # development directory
      - ./:/var/www/html/
      # expose apache logs to host
      - ./docker/log/:/var/log/apache2/
      # expose apache2 and php config to host
      - ./docker/etc/:/docker/etc/
      # expose ssl certificates to host
      - ./docker/ssl/:/etc/ssl/apache2/
